language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - pip install -U pip
  - pip install -U wheel setuptools pytest==3.2.5 flake8
  - pip install -q Django==$DJANGO_VERSION
  - pip install codecov
install:
  - python setup.py -q install
env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

matrix:
    exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.9
    - python: "3.3"
      env: DJANGO_VERSION=1.10
    - python: "3.3"
      env: DJANGO_VERSION=1.11
    - python: "3.5"
      env: DJANGO_VERSION=1.7

# command to run tests
script:
  - flake8 ./src
  - python setup.py test --addopts "--cov=./src/dynamic_fixtures"
after_success:
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
  - codecov
